name: build

on: [push, pull_request]

jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Lint Repository
        run: ./utils/asset-linter.sh

  sh-checker:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run sh-checker
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 4 -d
